### ISSUE TITLE
启动demo 后持续 lain_demo: Warning: Remote connection disconnect. Retrying...

### ISSUE THREAD

**Issue by jioll** [laincloud/lain-demo#1]
root@docker-vm-33-125 lain-demo]# vagrant up  
Bringing machine 'lain_demo' up with 'virtualbox' provider...
==> lain_demo: Checking if box 'laincloud/lain-demo' is up to date...
==> lain_demo: Clearing any previously set forwarded ports...
==> lain_demo: Clearing any previously set network interfaces...
==> lain_demo: Preparing network interfaces based on configuration...
    lain_demo: Adapter 1: nat
    lain_demo: Adapter 2: hostonly
==> lain_demo: Forwarding ports...
    lain_demo: 22 (guest) => 2222 (host) (adapter 1)
==> lain_demo: Running 'pre-boot' VM customizations...
==> lain_demo: Booting VM...
==> lain_demo: Waiting for machine to boot. This may take a few minutes...
    lain_demo: SSH address: 127.0.0.1:2222
    lain_demo: SSH username: vagrant
    lain_demo: SSH auth method: private key
    lain_demo: Warning: Remote connection disconnect. Retrying...
    lain_demo: Warning: Remote connection disconnect. Retrying...
    lain_demo: Warning: Remote connection disconnect. Retrying...
    lain_demo: Warning: Remote connection disconnect. Retrying...
    lain_demo: Warning: Remote connection disconnect. Retrying...
    lain_demo: Warning: Remote connection disconnect. Retrying...

**Comment by sunyi00** [comment]
这个看上去是虚拟机没有起来。有更多日志么？

**Comment by jioll** [comment]
2222端口有监听，telnet 127.0.0.1 2222 直接被断开了，像是ssh服务有问题；

[root@docker-vm-33-125 lain-demo]# vagrant halt
==> lain_demo: Attempting graceful shutdown of VM...
    lain_demo: Guest communication could not be established! This is usually because
    lain_demo: SSH is not running, the authentication information was changed,
    lain_demo: or some other networking issue. Vagrant will force halt, if
    lain_demo: capable.
==> lain_demo: Forcing shutdown of VM...

**Comment by wzyboy** [comment]
`root@docker-vm-33-125 lain-demo]# vagrant up`

看这行，你是在一台虚拟机里跑 Vagrant 么？

**Comment by jioll** [comment]
是啊，刚提醒了我，这个测试机是台VM的虚机；

**Comment by wzyboy** [comment]
@jioll Vagrant 本身就是虚拟机，在虚拟机里跑虚拟机不受支持。

**Comment by jioll** [comment]
@wzyboy  感谢~，我在物理机尝试跑一次~
